[package]
name = "agents"
version = "0.1.0"
edition = "2021"
description = "General Purpose Agents"
license = "Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
