[package]
name = "agents"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
openai = "1.0.0-alpha.13"
tokio = { version = "1.36", features = ["full"] }

[dev-dependencies]
dotenv = "0.15"